# Copyright (c) DataLab Platform Developers, BSD 3-Clause License
# See LICENSE file for details
"""Portable declarations for plugin-provided example workspaces."""

from __future__ import annotations

import dataclasses
import re
from collections.abc import Iterator, Mapping, Sequence
from contextlib import contextmanager
from importlib import resources
from importlib.abc import Traversable
from pathlib import Path, PurePosixPath
from types import MappingProxyType

from sigima.objects import ImageObj, SignalObj

_LOCAL_ID_PATTERN = re.compile(r"^[a-z0-9]+(?:[._-][a-z0-9]+)*$")
_PACKAGE_PATTERN = re.compile(
    r"^[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*$",
    flags=re.ASCII,
)


@dataclasses.dataclass(frozen=True)
class PluginExampleData:
    """Scientific objects and per-recipe defaults generated by a plugin.

    Args:
        objects: generated signals and images
        parameter_values: recipe ID to parameter values suited to these objects
    """

    objects: Sequence[SignalObj | ImageObj]
    parameter_values: Mapping[str, Mapping[str, object]] = dataclasses.field(
        default_factory=dict
    )

    def __post_init__(self) -> None:
        """Freeze and validate generated example data."""
        objects = tuple(self.objects)
        if not objects or not all(
            isinstance(obj, (SignalObj, ImageObj)) for obj in objects
        ):
            raise TypeError("Plugin example data must contain signal or image objects")
        if not isinstance(self.parameter_values, Mapping):
            raise TypeError("Plugin example parameters must map recipe IDs to values")
        frozen: dict[str, Mapping[str, object]] = {}
        for recipe_id, values in self.parameter_values.items():
            if not isinstance(recipe_id, str) or recipe_id.count(":") != 1:
                raise ValueError("Plugin example parameters must use recipe IDs")
            if not isinstance(values, Mapping) or not all(
                isinstance(key, str) for key in values
            ):
                raise TypeError(
                    "Plugin example parameters must map string keys to values"
                )
            frozen[recipe_id] = MappingProxyType(dict(values))
        object.__setattr__(self, "objects", objects)
        object.__setattr__(self, "parameter_values", MappingProxyType(frozen))

    def values_for(self, recipe_id: str) -> Mapping[str, object]:
        """Return the parameter values suited to one recipe (empty if none)."""
        return self.parameter_values.get(recipe_id, MappingProxyType({}))


@dataclasses.dataclass(frozen=True)
class PluginExample:
    """Packaged or generated example, and the recipes it was designed for.

    An example without recipe is presented as a plain dataset.
    """

    id: str
    title: str
    resource: str | None = None
    description: str = ""
    recipe_ids: Sequence[str] = ()
    expected_checks: Sequence[str] = ()

    def __post_init__(self) -> None:
        """Validate identity, package resource and workflow metadata."""
        if not isinstance(self.id, str) or not _LOCAL_ID_PATTERN.fullmatch(self.id):
            raise ValueError(
                "Plugin example ID must contain lowercase letters, digits, '.', "
                "'_' or '-'"
            )
        if not isinstance(self.title, str) or not self.title.strip():
            raise ValueError("Plugin example title must be a non-empty string")
        if not isinstance(self.description, str):
            raise TypeError("Plugin example description must be a string")
        if self.resource is not None and (
            not isinstance(self.resource, str) or self.resource.count(":") != 1
        ):
            raise ValueError("Plugin example resource must use 'package:path' syntax")
        if self.resource is not None:
            if not _PACKAGE_PATTERN.fullmatch(self.package):
                raise ValueError("Plugin example resource package is invalid")
            path = PurePosixPath(self.resource_path)
            if (
                not self.resource_path
                or "\\" in self.resource_path
                or path.is_absolute()
                or ".." in path.parts
            ):
                raise ValueError("Plugin example resource path must be relative")
        if isinstance(self.recipe_ids, (str, bytes)) or not isinstance(
            self.recipe_ids, Sequence
        ):
            raise TypeError("Plugin example recipe IDs must be a sequence")
        recipe_ids = tuple(self.recipe_ids)
        if not all(
            isinstance(recipe_id, str) and recipe_id.count(":") == 1
            for recipe_id in recipe_ids
        ):
            raise ValueError("Plugin example recipe IDs must be namespaced")
        if len(recipe_ids) != len(set(recipe_ids)):
            raise ValueError("Plugin example recipe IDs must be unique")
        object.__setattr__(self, "recipe_ids", recipe_ids)
        if isinstance(self.expected_checks, (str, bytes)) or not isinstance(
            self.expected_checks, Sequence
        ):
            raise TypeError("Plugin example expected checks must be a sequence")
        checks = tuple(self.expected_checks)
        if not all(isinstance(check, str) and check.strip() for check in checks):
            raise ValueError("Plugin example expected checks must be non-empty strings")
        if len(checks) != len(set(checks)):
            raise ValueError("Plugin example expected checks must be unique")
        object.__setattr__(self, "expected_checks", checks)

    @property
    def package(self) -> str:
        """Return the importable package containing the example resource."""
        if self.resource is None:
            raise ValueError("Generated plugin example has no package resource")
        return self.resource.split(":", maxsplit=1)[0]

    @property
    def resource_path(self) -> str:
        """Return the POSIX-style path relative to the resource package."""
        if self.resource is None:
            raise ValueError("Generated plugin example has no package resource")
        return self.resource.split(":", maxsplit=1)[1]

    def resolve(self) -> Traversable:
        """Resolve the declared resource without requiring a filesystem path."""
        resource = resources.files(self.package)
        for part in PurePosixPath(self.resource_path).parts:
            resource = resource.joinpath(part)
        if not resource.is_file():
            raise FileNotFoundError(
                f"Plugin example resource not found: {self.resource}"
            )
        return resource

    @contextmanager
    def as_file(self) -> Iterator[Path]:
        """Materialize the resource for APIs that require a filesystem path."""
        with resources.as_file(self.resolve()) as filename:
            yield Path(filename)


__all__ = ["PluginExample", "PluginExampleData"]
